spring:
  application:
    name: Mindfit API
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:mindfit_app}
    password: ${SPRING_DATASOURCE_PASSWORD:mindfit}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        hbm2ddl:
          auto: create
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-4.1-nano
  docker:
    compose:
      enabled: false

server:
  port: 8088
  tomcat:
    max-http-request-header-size: 8KB
    max-http-form-post-size: 2MB
    connection-timeout: 5000
    reject-illegal-header: true
  error:
    include-stacktrace: never
    include-message: never

app:
  jwt:
    secret: mySecretKeyForDevelopmentPleaseChangeInProduction
    expiration-ms: 86400000
  cors:
    # Comma-separated list of allowed origins for CORS (adjust as needed)
    allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:5173,http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.mindfit: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  docker:
    compose:
      enabled: false

app:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration-ms: 86400000
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.mindfit: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.tool.schema: DEBUG
